

export const SUPPORTED_LANGUAGES = [
    { code: 'af', label: '🇿🇦 Afrikaans' },
{ code: 'sq', label: '🇦🇱 Albanian' },
{ code: 'ar', label: '🇸🇦 Arabic' },
{ code: 'hy', label: '🇦🇲 Armenian' },
{ code: 'bn', label: '🇧🇩 Bengali' },
{ code: 'bs', label: '🇧🇦 Bosnian' },
{ code: 'bg', label: '🇧🇬 Bulgarian' },
{ code: 'ca', label: '🇪🇸 Catalan' },
{ code: 'ceb', label: '🇵🇭 Cebuano' },
{ code: 'zh-CN', label: '🇨🇳 Chinese (Simp)' },
{ code: 'zh-TW', label: '🇹🇼 Chinese (Trad)' },
{ code: 'hr', label: '🇭🇷 Croatian' },
{ code: 'cs', label: '🇨🇿 Czech' },
{ code: 'da', label: '🇩🇰 Danish' },
{ code: 'nl', label: '🇳🇱 Dutch' },
{ code: 'en', label: '🇺🇸 English' },
{ code: 'et', label: '🇪🇪 Estonian' },
{ code: 'tl', label: '🇵🇭 Filipino' },
{ code: 'fi', label: '🇫🇮 Finnish' },
{ code: 'fr', label: '🇫🇷 French' },
{ code: 'de', label: '🇩🇪 German' },
{ code: 'el', label: '🇬🇷 Greek' },
{ code: 'gu', label: '🇮🇳 Gujarati' },
{ code: 'hi', label: '🇮🇳 Hindi' },
{ code: 'hu', label: '🇭🇺 Hungarian' },
{ code: 'id', label: '🇮🇩 Indonesian' },
{ code: 'it', label: '🇮🇹 Italian' },
{ code: 'ja', label: '🇯🇵 Japanese' },
{ code: 'jv', label: '🇮🇩 Javanese' },
{ code: 'kn', label: '🇮🇳 Kannada' },
{ code: 'ko', label: '🇰🇷 Korean' },
{ code: 'la', label: '🏛️ Latin' },
{ code: 'lv', label: '🇱🇻 Latvian' },
{ code: 'lt', label: '🇱🇹 Lithuanian' },
{ code: 'ms', label: '🇲🇾 Malay' },
{ code: 'ml', label: '🇮🇳 Malayalam' },
{ code: 'mr', label: '🇮🇳 Marathi' },
{ code: 'ne', label: '🇳🇵 Nepali' },
{ code: 'no', label: '🇳🇴 Norwegian' },
{ code: 'fa', label: '🇮🇷 Persian' },
{ code: 'pl', label: '🇵🇱 Polish' },
{ code: 'pt', label: '🇵🇹 Portuguese' },
{ code: 'pa', label: '🇮🇳 Punjabi' },
{ code: 'ro', label: '🇷🇴 Romanian' },
{ code: 'ru', label: '🇷🇺 Russian' },
{ code: 'sr', label: '🇷🇸 Serbian' },
{ code: 'sk', label: '🇸🇰 Slovak' },
{ code: 'sl', label: '🇸🇮 Slovenian' },
{ code: 'es', label: '🇪🇸 Spanish' },
{ code: 'sw', label: '🇰🇪 Swahili' },
{ code: 'sv', label: '🇸🇪 Swedish' },
{ code: 'ta', label: '🇮🇳 Tamil' },
{ code: 'te', label: '🇮🇳 Telugu' },
{ code: 'th', label: '🇹🇭 Thai' },
{ code: 'tr', label: '🇹🇷 Turkish' },
{ code: 'uk', label: '🇺🇦 Ukrainian' },
{ code: 'ur', label: '🇵🇰 Urdu' },
{ code: 'vi', label: '🇻🇳 Vietnamese' },
{ code: 'cy', label: '🏴󠁧󠁢󠁷󠁬󠁳󠁿 Welsh' },
{ code: 'yi', label: '✡️ Yiddish' },
{ code: 'zu', label: '🇿🇦 Zulu' }
];
